version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: overlord880/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: overlord880/post:1.0
    networks:
      - reddit
  comment:
    build: ./comment
    image: overlord880/comment:1.0
    networks:
      - reddit
volumes:
  post_db:

networks:
  reddit: